### PR TITLE
fix(tabs): fix customClass [fixes #2253]

### LINKED ISSUE #2253: Custom class is not getting applied
In tabs while setting custom css class is not applying to the tab component.  `<tab heading="Static title" customClass="customClass">Static content</tab>`
http://valor-software.com/ngx-bootstrap/#/tabs#styling

### PR DESCRIPTION
**Pull request by IlyaSurmay**

### CODE REVIEW

File: src/tabs/tab.directive.ts [hunk 1]
```diff
@@ -13,15 +13,24 @@ export class TabDirective implements OnInit, OnDestroy {
   /** if true tab can be removable, additional button will appear */
   @Input() public removable: boolean;
   /** if set, will be added to the tab's class atribute */
-  @Input() public customClass: string;
+  @Input() public get customClass(): string {
+    return this._customClass;
+  }
+
+  public set customClass(customClass: string) {
+    if (customClass) {
```
Comment (valorkin) [inline src/tabs/tab.directive.ts]:
```js
if (this._customClass && this._customClass !== customClass) {
  this.renderer.setElementClass(this.elementRef.nativeElement, this._customClass, false);
}
if (customClass) {
....
}
```
