### PR TITLE
fix(demo): Fixed routings issue for links with inner html tags.

### LINKED ISSUE #3813: fix(demo): fix routing functionality for links with inner html tags for demo pages
Fix routing for links on demo pages with `href="#"` and inner html tags.

### Actrual result
If there is any inner html tag inside link, for example `<a href="#"><span>Some text</span></a>`,
this link will redirect to homepage.
### Expected result
All links on demo pages with `href = #` should do nothing, even with inner html tags

### PR DESCRIPTION
**Pull request by ghost**
Fixed routings issue for links with inner html tags.
this pr should be merged before pr #3812

Closes #3813

### CODE REVIEW

File: demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export class ExamplesComponent {
 
   @HostListener('document:click', ['$event'])
   preventEmptyHrefNav(event: Event) {
-    if (event && event.target && (event.target as Element).getAttribute('href') === '#') {
+    if (event && event.target && (event.target as Element).getAttribute('href') === '#' || event.srcElement.parentElement && (event.srcElement.parentElement as Element).getAttribute('href') === '#') {
```
Comment (IlyaSurmay) [inline demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts]: what if we have following structure:
```
<a href="#">
   <p>Text <b>text</b></p>
</a>
```
when you click on `<b>` you'll be redirected to the homepage. 
you should look for all tree of parent elements, not just the closest parent

**Review by IlyaSurmay — CHANGES_REQUESTED** [review]

File: demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts [hunk 2]
```diff
@@ -16,9 +16,24 @@ export class ExamplesComponent {
...
+    if (element.nodeName !== link) {
+      while (element !== document.body)  {
+        if (linkPrevent) {
+          event.preventDefault();
+          break;
+        }
+        element = element.parentElement;
+        linkPrevent = event && element && (element as Element).getAttribute('href') === '#';
+      }
+    } else {
```
Comment (IlyaSurmay) [inline demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts]: avoid using `else`. Use `if () {... return;}` instead

File: demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts [hunk 3]
```diff
@@ -16,9 +16,24 @@ export class ExamplesComponent {
   }
 
   @HostListener('document:click', ['$event'])
-  preventEmptyHrefNav(event: Event) {
-    if (event && event.target && (event.target as Element).getAttribute('href') === '#') {
-      event.preventDefault();
+  preventEmptyHrefNav(event: Event): void {
+    let element = event.srcElement;
```
Comment (IlyaSurmay) [inline demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts]: why `srcElement`? this won't work in Firefox. use `target`

**Review by IlyaSurmay — CHANGES_REQUESTED** [review]

File: demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts [hunk 4]
```diff
@@ -16,9 +16,24 @@ export class ExamplesComponent {
   }
 
   @HostListener('document:click', ['$event'])
-  preventEmptyHrefNav(event: Event) {
-    if (event && event.target && (event.target as Element).getAttribute('href') === '#') {
+  preventEmptyHrefNav(event: Event): any {
+    let element: any = event.target;
+    let linkPrevent = event && element.getAttribute('href') === '#';
```
Comment (IlyaSurmay) [inline demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts]: linkPrevent -> preventNav

**Review by IlyaSurmay — CHANGES_REQUESTED** [review]

File: demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts [hunk 5]
```diff
@@ -16,9 +16,24 @@ export class ExamplesComponent {
   }
 
   @HostListener('document:click', ['$event'])
-  preventEmptyHrefNav(event: Event) {
-    if (event && event.target && (event.target as Element).getAttribute('href') === '#') {
+  preventEmptyHrefNav(event: Event): any {
+    let element: any = event.target;
+    let preventNav = event && element.getAttribute('href') === '#';
```
Comment (IlyaSurmay) [inline demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts]: remove `event &&`, it can't be undefined

File: demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts [hunk 6]
```diff
@@ -16,9 +16,24 @@ export class ExamplesComponent {
...
+    }
+
+    if (element.tagName !== 'A') {
+      while (element !== document.body)  {
+        if (preventNav) {
+          event.preventDefault();
+          return;
+        }
+        element = element.parentElement;
+        preventNav = event && element.getAttribute('href') === '#';
```
Comment (IlyaSurmay) [inline demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts]: same

**Review by IlyaSurmay — CHANGES_REQUESTED** [review]

**Review by IlyaSurmay — DISMISSED** [review]

**Comment by YevheniiaMazur** [comment]
Tested, looks good

File: demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts [hunk 7]
```diff
@@ -16,9 +16,24 @@ export class ExamplesComponent {
   }
 
   @HostListener('document:click', ['$event'])
-  preventEmptyHrefNav(event: Event) {
-    if (event && event.target && (event.target as Element).getAttribute('href') === '#') {
+  preventEmptyHrefNav(event: Event): any {
+    let element: any = event.target;
```
Comment (valorkin) [inline demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts]: @svetoldo4444ka please set proper type here

**Review by valorkin — CHANGES_REQUESTED** [review]

**Comment by ghost** [comment]
@valorkin fixed it

**Review by valorkin — APPROVED** [review]
