### PR TITLE
fix(typeahead): fix close on blur

### LINKED ISSUE #2588: Typeahead within modal closes when scrollbar is clicked
Here's a plunker:
https://plnkr.co/edit/r0xqdcLOmGzfEYKc7H8r

Don't click "open modal" button just yet.
Type something (ex: letter a) in the input box, make your browser window small enough so you have a scrollbar on the "run" window. Play with scrollbar - everything works as expected.

Now open the modal window and try the same within it (there's another typeahead control). As soon as you touch the scrollbar control closes (receives blur event)

### PR DESCRIPTION
**Pull request by IlyaSurmay**
Fixes #2588 

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.

### CODE REVIEW

File: src/typeahead/typeahead.directive.ts [hunk 1]
```diff
@@ -276,6 +276,10 @@ export class TypeaheadDirective implements OnInit, OnDestroy {
         dropup: this.dropup
       });
 
+    this._outsideClickListener = this.renderer.listen('document', 'click', () => {
```
Comment (valorkin) [inline src/typeahead/typeahead.directive.ts:279]: host('document:click') ?

Comment (IlyaSurmay) [reply src/typeahead/typeahead.directive.ts:279]: It was done this way to achieve better performance. A lot of host listeners will decrease it so I decided to attach listener only when box with results is open.
