### PR TITLE
fix(progressbar): add aria-valuemax fix

### LINKED ISSUE #5957: NGX-Bootstrap Progressbar Component not updating aria-valuemax attribute
**Bug description:**

The **ProgressbarComponent** is not getting updated with the **aria-valuemax** attribute. Other aria attributes such **aria-valuenow** and **aria-valuetext** are getting updated whenever the **currentValue** or the **maxValue** of the **Progressbar** changes.
But the **aria-valuemax** attribute is not getting appended to the element even on load of the component.

This issue is reproducible in the **NGX-Bootstrap's** demo site:

https://valor-software.com/ngx-bootstrap/#/progressbar

**aria-valuemax** attribute not present in the below **Progressbar** example from **NGX-Bootstrap** Demo site:
image

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: v5.6.1

Angular: v9.1.4

Bootstrap: v3.4.1

Build system: Angular CLI, System.js, webpack, starter seed:

**Expected behavior**

The **aria-valuemax** attribute should get appended to the **BarComponent** and also it should get updated whenever the **maxValue** changes.

**Root Cause**

The issue is with the "max" property of the **BarComponent** which is in-turn binded to the **aria-valuemax** attribute.
But this **"max"** property is neither an "@Input" like the **"value"** nor is updated whenever the **maxValue** changes.
It always remains undefined.

image

**Solution**

The **"max"** should be an "@Input" property so that it can be passed to the **BarComponent** from the **ProgressbarComponent** and so the **aria-valuemax** attribute will get updated whenever the **maxValue** changes.

### PR DESCRIPTION
**Pull request by daniloff200**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

fixes #5957

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

File: src/progressbar/bar.component.ts [hunk 1]
```diff
@@ -30,7 +30,15 @@ import { isBs3 } from 'ngx-bootstrap/utils';
...
 export class BarComponent implements OnInit, OnDestroy {
-  max: number;
+  @Input()
+  get max(): number {
+    return this._max;
+  }
+
+  set max(v: number) {
+    this._max = v;
+    this.applyTypeClasses();
```
Comment (valorkin) [inline src/progressbar/bar.component.ts]: please move this to `OnChange ` and react only on type\max changes

**Review by valorkin — CHANGES_REQUESTED** [review]
one small change please

File: src/progressbar/bar.component.ts (hunk 1 above)
Comment (daniloff200) [reply src/progressbar/bar.component.ts]: done

**Review by valorkin — APPROVED** [review]
Looks good to me

File: src/progressbar/progressbar.component.html [hunk 2]
```diff
@@ -1,6 +1,6 @@
-<bar [type]="type" [value]="_value" *ngIf="!isStacked">
+<bar [type]="type" [value]="_value" [max]="_max" *ngIf="!isStacked">
   <ng-content></ng-content>
 </bar>
 <ng-template [ngIf]="isStacked">
-  <bar *ngFor="let item of _value" [type]="item.type" [value]="item.value">{{ item.label }}</bar>
+  <bar *ngFor="let item of _value" [type]="item.type" [value]="item.value" [max]="item.max">{{ item.label }}</bar>
```
Comment (Sebi11) [inline src/progressbar/progressbar.component.html:5]: Hello!
I'm afraid this fix has broken the `max` attribute when using a "stacked" progress bar. This small piece of code requires each item of `BarValue` to have the same `max` attribute, rather than using the `max` input of the `ProgressbarComponent`.
