### PR TITLE
fix(typeahead): fix flickering

### LINKED ISSUE #3315: Typeahead is flickering
### Bug description:
When focusing the typeahead input with ([typeaheadMinLength]="0") the list that will be shown is flickering sometimes.

### Plunker/StackBlitz that reproduces the issue:
The issue also exists in the current typeahead examples:
https://valor-software.com/ngx-bootstrap/#/typeahead#reactive-forms

I recommend using **Google Chrome** to reproduce this issue. The problem does not occur that often in IE11 and Firefox. Focus and leave the typeahead input constantly to see whats up. Info: I think the effect is even bigger if you use a larger list.

Greetings

### PR DESCRIPTION
**Pull request by IlyaSurmay**
Fixes #3315 
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

File: src/typeahead/typeahead.directive.ts [hunk 1]
```diff
@@ -291,7 +291,13 @@ export class TypeaheadDirective implements OnInit, OnDestroy {
         dropup: this.dropup
       });
 
-    this._outsideClickListener = this.renderer.listen('document', 'click', () => {
+    this._outsideClickListener = this.renderer.listen('document', 'click', (e: MouseEvent) => {
+      if (this.typeaheadMinLength === 0) {
```
Comment (valorkin) [inline src/typeahead/typeahead.directive.ts]: make it one `if` with return

**Review by valorkin — CHANGES_REQUESTED** [review]

**Review by valorkin — APPROVED** [review]
