### PR TITLE
fix(datepicker): datepicker not closed on Enter click in IE11

### LINKED ISSUE #5617: Datepicker does not close on enter in IE11
I have an issue with the datepicker in Internet Explorer 11. It does not close on enter when typing a date manually (not picking one via the datepicker). You have to click outside to get it to close, while it automatically closes on enter in all other browsers. I can reproduce it in the examples in the documentation (https://valor-software.com/ngx-bootstrap/#/datepicker), so it's not just my code.

### PR DESCRIPTION
**Pull request by daniloff200**
closes #5617
On Google Chrome and Firefox this functionality worked before, but, I also checked this code in them no issues were caused by this condition.

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

File: src/datepicker/bs-daterangepicker-input.directive.ts [hunk 1]
```diff
@@ -99,6 +100,13 @@ export class BsDaterangepickerInputDirective
     });
   }
 
+  onKeydownEvent(event) {
+    if (event.keyCode === 13 || event.code === 'Enter') {
+      this.hide();
+    }
+  }
+
+
```
Comment (dmitry-zhemchugov) [inline src/datepicker/bs-daterangepicker-input.directive.ts]: Delete empty line

**Review by dmitry-zhemchugov — DISMISSED** [review]
Working as expected

**Review by IraErshova — APPROVED** [review]
