### PR TITLE
fix(datepicker): added optional time initing

### LINKED ISSUE #6276: Datepicker modifies initial value after update from 6.2.0 to 7.0.0
**Bug description:**
After updating from 6.2.0 to 7.0.0, the datepicker changes the time of any `Date` value that is set to the users current local time. This also happens when the datepicker is used in a form and an initial value is set. This causes the initial form value to change, while the user has not made any changes. Also, setting the time of the `Date` value to the current time makes no sense, since the time of selection is not in any way relevant to the selected date.

The commit that causes this: https://github.com/valor-software/ngx-bootstrap/commit/bc188d69bf17010dadd924673bfa13eef3944833

I suggest that this behaviour be removed again. Alternatively, it might make more sense to set the time to start of day on the selected date.

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

ngx-bootstrap: 7.0.0

Angular: 12.1.4

Bootstrap: 4.5.3

**Expected behavior**

Expected behaviour would be that the initial `Date` value is set without modifications.

### PR DESCRIPTION
**Pull request by SvetlanaMuravlova**
fix(datepicker): added optional time initing
closes #6276  #6260

### CODE REVIEW

**Review by daniloff200 — DISMISSED** [review]

File: src/datepicker/bs-datepicker-inline.component.ts [hunk 1]
```diff
@@ -31,7 +31,13 @@ export class BsDatepickerInlineDirective implements OnInit, OnDestroy, OnChanges
   /**
    * Config object for datepicker
    */
-  @Input() bsConfig?: Partial<BsDatepickerInlineConfig>;
+  @Input() set bsConfig(value: Partial<BsDatepickerInlineConfig>) {
```
Comment (valorkin) [inline src/datepicker/bs-datepicker-inline.component.ts]: move to ngOnChanges

File: src/datepicker/bs-datepicker-inline.component.ts [hunk 2]
```diff
@@ -179,15 +181,16 @@ export class BsDatepickerInlineDirective implements OnInit, OnDestroy, OnChanges
       this._datepicker.hide();
     }
 
-    this._config = Object.assign({}, this._config, this.bsConfig, {
-      value: checkBsValue(this._bsValue, this.maxDate || this.bsConfig && this.bsConfig.maxDate),
+    this._config = Object.assign({}, this._config, this._bsConfig, {
```
Comment (valorkin) [inline src/datepicker/bs-datepicker-inline.component.ts]: revert

**Review by valorkin — CHANGES_REQUESTED** [review]
please apply comments

**Review by valorkin — DISMISSED** [review]
