### PR TITLE
fix (acordion) space beetween accordion groups

### LINKED ISSUE #1854: No space beetween accordion groups
In pure bootstrap there is a space between panels in panel-group implemented by css rule

    .panel-group .panel + .panel {
        margin-top: 5px;
    }
But in ng2-bootstrap each panel is wrapped in accordion-group tag so the rule does not apply eliminating space between groups.

Example - good - bootstrap v3.3.7 + angular-ui-bootstrap 2.2.0 + angular 1.5.8
old

Example - bad - bootstrap v3.3.7 + ng2-bootstrap 1.6.0 + angular 2.4.9
new

### PR DESCRIPTION
**Pull request by artemvfrolov**
fixed #1854

### CODE REVIEW

**Comment by YevheniiaMazur** [comment]
Tested. For bootstrap 3 spaces was fixed. For bootstrap 4 there are no spaces, but this accordion style is used in bootstrap 4 https://v4-alpha.getbootstrap.com/components/collapse/

**Review by valorkin — APPROVED** [review]

File: src/accordion/accordion-group.component.ts [hunk 1]
```diff
@@ -14,22 +14,26 @@ import { AccordionComponent } from './accordion.component';
...
   template: `
-<div class="panel card" [ngClass]="panelClass">
-  <div class="panel-heading card-header" role="tab" (click)="toggleOpen($event)">
-    <div class="panel-title">
-      <div role="button" class="accordion-toggle" [attr.aria-expanded]="isOpen">
-        <div *ngIf="heading"[ngClass]="{'text-muted': isDisabled}">{{heading}}</div>
-        <ng-content select="[accordion-heading]"></ng-content>
+    <div class="panel card" [ngClass]="panelClass">
+      <div class="panel-heading card-header" role="tab" (click)="toggleOpen($event)">
+        <div class="panel-title card-title">
```
Comment (7185) [inline src/accordion/accordion-group.component.ts:19]: You might need to rebase, considering #2024
