### PR TITLE
fix(modals): fix minimize Safari after press esc

### LINKED ISSUE #3313: fix(modals): after opening any modal and pressing Esc button, browser minimize and only after that modal dissappears
### Bug description:
- Open ngx-bootstrap demo at Safari browser
- Open modal demo page
- Click on any button for showing modal
- Press Esc button
### Expected result
After pressing Esc button Modal hides, and browser window doesn't change it's size

modaldemoissue
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: all supported

Angular: all supported

Bootstrap: all supported

### PR DESCRIPTION
**Pull request by artolshansky**
fix: after opening any modal and pressing Esc button, browser minimize and only after that modal dissappears

close #3313

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.

### CODE REVIEW

**Review by IlyaSurmay — DISMISSED** [review]

**Comment by YevheniiaMazur** [comment]
tested, looks good

File: src/modal/modal-container.component.ts [hunk 1]
```diff
@@ -88,8 +88,12 @@ export class ModalContainerComponent implements OnInit, OnDestroy {
     this.hide();
   }
 
-  @HostListener('window:keydown.esc')
-  onEsc(): void {
+  @HostListener('keydown.esc', ['$event'])
```
Comment (valorkin) [inline src/modal/modal-container.component.ts]: if focus will be outside of modal 
what is possible without focus trap in place
pressing esc will not close modal

**Review by valorkin — CHANGES_REQUESTED** [review]
TBD

**Review by valorkin — APPROVED** [review]
