### PR TITLE
fix(modal): change the mouse event to dismiss a modal on backdrop click

### LINKED ISSUE #5264: Modal closes on release of mouse outside modal box
I have built an example that will guide you through the odd behavior of modals:

https://stackblitz.com/edit/ngx-bootstrap-qdilhe?file=app/app.module.ts

To make it simple, If you click inside the modal, but drag and release the mouse outside the modal, the modal is dismissed nevertheless. This behavior only happens on `ngx-bootstrap`, not on bootstrap's modal.

### PR DESCRIPTION
**Pull request by florenthobein**
Because of the use of a 'click' event to trigger the dismissal of a modal, the target of the event doesn't take into account an eventual movement of the mouse before releasing click (for ex. selection of text), which can lead to unwanted dismissal of the modal.

Closes: #5264

# PR Checklist

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation (not needed)
 - [x] added/updated demos (not needed)

### CODE REVIEW

File: src/modal/modal-container.component.ts [hunk 1]
```diff
@@ -76,12 +77,18 @@ export class ModalContainerComponent implements OnInit, OnDestroy {
     }
   }
 
-  @HostListener('click', ['$event'])
-  onClick(event: MouseEvent): void {
+  @HostListener('mousedown', ['$event'])
+  onClickStarted(event: MouseEvent): void {
+    this.clickStartedInside = event.target !== this._element.nativeElement;
```
Comment (benjaminrau) [inline src/modal/modal-container.component.ts]: Property name or condition should be changed. Actually this evals to clickStartedOutside.
Changing condition would result in
`this.clickStartedInside = event.target === this._element.nativeElement;`

File: src/modal/modal-container.component.ts [hunk 2]
```diff
@@ -76,12 +77,18 @@ export class ModalContainerComponent implements OnInit, OnDestroy {
...
+  }
+
+  @HostListener('mouseup', ['$event'])
+  onClickStop(event: MouseEvent): void {
+    const clickedInside = this.clickStartedInside || event.target !== this._element.nativeElement;
```
Comment (benjaminrau) [inline src/modal/modal-container.component.ts]: IMO should be
`const clickedOutside = !this.clickStartedInside || event.target !== this._element.nativeElement;`

File: src/modal/modal-container.component.ts [hunk 3]
```diff
@@ -76,12 +77,18 @@ export class ModalContainerComponent implements OnInit, OnDestroy {
...
     if (
       this.config.ignoreBackdropClick ||
       this.config.backdrop === 'static' ||
-      event.target !== this._element.nativeElement
+      clickedInside
```
Comment (benjaminrau) [inline src/modal/modal-container.component.ts]: Should be changed then to use `clickedOutside `

File: src/modal/modal-container.component.ts [hunk 4]
```diff
@@ -76,12 +77,18 @@ export class ModalContainerComponent implements OnInit, OnDestroy {
...
     ) {
       return;
     }
```
Comment (benjaminrau) [inline src/modal/modal-container.component.ts:96]: You could consider to reset`clickStartedInside` to default value after it was used for condition to not use a previous result of onClickStart if there was not mousedown inside but rather only mouseup.

**Review by benjaminrau — CHANGES_REQUESTED** [review]
Thanks for the fix which is bugging us also. I tried to provide a review.

File: src/modal/modal-container.component.ts [hunk 5]
```diff
@@ -38,6 +38,7 @@ export class ModalContainerComponent implements OnInit, OnDestroy {
   isAnimated: boolean;
   bsModalService: BsModalService;
   private isModalHiding = false;
+  private clickStartedInside = true;
```
Comment (benjaminrau) [inline src/modal/modal-container.component.ts]: The default value should be `false` because if there is no mousedown (started outside) the constraint is not checked if it started inside but value would be true.

**Review by benjaminrau — CHANGES_REQUESTED** [review]

File: src/modal/modal-container.component.ts (hunk 1 above)
Comment (florenthobein) [reply src/modal/modal-container.component.ts]: You're right, there is a misunderstanding in the naming. `this._element.nativeElement` evaluates to the backdrop, that's why if `event.target` is different, it means we didn't click on the backdrop, hence we clicked on the modal. So a more precise name would be `clickStartedInsideModalContainer` (or `clickStartedOutsideBackdrop` but it feels like a double negative)

**Comment by benjaminrau** [comment]
@florenthobein We tested your changes in our project and it didnt fix the issue in first place.
We use ModalDirective instead of the Component. After we applied your changes on the directive it is fixed in both.

I think the Directive should be fixed within this pull request also.

**Review by korinovsky — DISMISSED** [review]

**Comment by Lexikus** [comment]
How is this task going? It might fix a problem that I have.

**Comment by florenthobein** [comment]
I just pushed an updated version taking in consideration comments about variable naming & including this fix in the context of a directive.

Sadly enough, there is no shared code between the `ModalDirective` and the `ModalContainerComponent`. I didn't take the risk to initiate a refactoring of this component, and had to duplicate part of the logic.

Tests are OK. Any update on a potential merge? 🙏

**Comment by daniloff200** [comment]
Sorry for the long delay, I'm gonna review it and share with the QA team very soon

**Comment by florenthobein** [comment]
There is something I would like to get your attention on, I have a strange behavior on my app using this patch and I'm not quite sure it's linked to this PR yet. When trying to scroll the modal using the mouse on scrollbar (drag&drop of the scrollbar), it closes the modal (verified on Chrome on a Macbook without mouse plugged). Do you reproduce this same behavior?

**Review by valorkin — APPROVED** [review]
thanks for contribution, looks good to me

**Comment by daniloff200** [comment]
@florenthobein well, I hope @dmitry-zhemchugov  will help us to find out, is it an issue, related to this PR, or, something new, or, some special use case, which you found suddenly!

**Comment by dmitry-zhemchugov** [comment]
via Hubstaff
User: Dmitry Zhemchugov

Project: int_ngx-bootstrap (OSS) - https://app.hubstaff.com/projects/304822
Date Range: 01/20/20 - 01/20/20
Work session total: 5:32:25
Billable: Yes

Grand total: 5:32:25
