### PR TITLE
fix(typeahead): fixed onblur event

### LINKED ISSUE #6025: typeahead typeaheadOnBlur not working
Event not triggered ?

see demo page https://valor-software.com/ngx-bootstrap/#/typeahead#on-blur
Option on blur:  
remains for ever empty....

### PR DESCRIPTION
**Pull request by SvetlanaMuravlova**
fix(typeahead): fixed onblur event
close #6025

### CODE REVIEW

File: libs/doc-pages/typeahead/src/lib/demos/on-blur/on-blur.ts [hunk 1]
```diff
@@ -1,10 +1,11 @@
 import { Component } from '@angular/core';
-import { TypeaheadMatch } from 'ngx-bootstrap/typeahead';
+import { TypeaheadMatch, TypeaheadConfig } from 'ngx-bootstrap/typeahead';
 
 @Component({
   // eslint-disable-next-line @angular-eslint/component-selector
   selector: 'demo-typeahead-on-blur',
-  templateUrl: './on-blur.html'
+  templateUrl: './on-blur.html',
+  providers: [{ provide: TypeaheadConfig, useValue: { chooseItemOnBlur: true, hideResultsOnBlur: true } }]
```
Comment (valorkin) [inline libs/doc-pages/typeahead/src/lib/demos/on-blur/on-blur.ts]: selectItemOnBlur

File: src/typeahead/typeahead-container.component.ts [hunk 2]
```diff
@@ -197,6 +197,10 @@ export class TypeaheadContainerComponent implements OnDestroy {
     return this.parent ? this.parent.typeaheadItemTemplate : undefined;
   }
 
+  get allowChooseItemsOnBlur(): boolean {
```
Comment (valorkin) [inline src/typeahead/typeahead-container.component.ts]: canSelectItemsOnBlur

File: src/typeahead/typeahead-container.component.ts [hunk 3]
```diff
@@ -295,6 +299,10 @@ export class TypeaheadContainerComponent implements OnDestroy {
   @HostListener('blur')
   focusLost(): void {
     this.isFocused = false;
+    if (this.allowChooseItemsOnBlur) {
```
Comment (valorkin) [inline src/typeahead/typeahead-container.component.ts]:
```ts
if (!this.canSelectItemOnBlur) {
  this.setActive(void 0);
}
```

**Review by valorkin — CHANGES_REQUESTED** [review]
please apply comments

**Review by valorkin — APPROVED** [review]
